version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: docker/dockerfile
    restart: always
    container_name: adonis
    tty: true
    env_file:
      - src/.env
    ports:
      - 3333:3333
    networks:
      - gateway

networks:
  gateway:
