version: '3'
services:
  backend:
    build: .
    restart: always
    container_name: adonis
    tty: true
    networks:
      - gateway
    env_file:
      - .env
    ports:
      - 3333:3333
    logging:
        driver: "awslogs"
        options:
           awslogs-region: "ap-southeast-1"
           awslogs-group: "adonis"
           awslogs-stream: "adonis"

networks:
  gateway:
    external: true
