version: '3'

services:
  adonis-mysql:
    image: mysql
    container_name: "${APP_NAME}_MYSQL"
    platform: 'linux/x86_64'
    ports:
      - '3366:3306'
    volumes:
      - $PWD/data:/var/lib/mysql
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - adonis-network

  adonis-phpmyadmin:
    container_name: "${APP_NAME}_PMA"
    image: phpmyadmin/phpmyadmin
    depends_on:
      - adonis-mysql
    environment:
      PMA_HOST: adonis-mysql
    ports:
      - '8585:80'
    restart: 'always'
    volumes:
      - /phpmyadmin
    networks:
      - adonis-network

  adonis-app:
    container_name: "${APP_NAME}_APP"
    build:
      context: .
      dockerfile: dockerfile-dev
    volumes:
      - src/:/app
      - /app/node_modules
    restart: 'always'
    environment:
      PORT: 3330
    env_file:
      - src/.env
    ports:
      - "3330:3330"
    depends_on:
      - adonis-mysql
    networks:
      - adonis-network

networks:
  adonis-network:
