version: '3'

services:
  adonis-mysql:
    image: mysql
    container_name: "${APP_NAME}_MYSQL"
    ports:
      - '3366:3306'
    volumes:
      - $PWD/data:/var/lib/mysql
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - adonis-network

  redis:
    image: redis
    container_name: "${APP_NAME}_REDIS"
    restart: always
    networks:
      - adonis-network
    expose:
      - 6379

  adonis-app:
    container_name: "${APP_NAME}_APP"
    build:
      context: .
      dockerfile: docker/dockerfile-dev
    volumes:
      - ./src:/app
      - /app/node_modules
    restart: 'always'
    environment:
      PORT: 3330
      DB_HOST: adonis-mysql
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file:
      - src/.env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - adonis-mysql
      - redis
    networks:
      - adonis-network

networks:
  adonis-network:
