FROM node:12

ENV HOME=/app
RUN mkdir /app 

RUN apt-get update

COPY src/package.json $HOME

WORKDIR $HOME

RUN npm install && npm i -g @adonisjs/cli && npm install -g nodemon

EXPOSE 3330

CMD [ "nodemon", "server.js" ]

