# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: CI

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - '.github/**'
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - '.github/**'

jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./src
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: '14'
    - run: npm install
      working-directory: ${{ env.working-directory }}
    - run: cp .env.testing .env
      working-directory: ${{ env.working-directory }}
    - run: npm run test
      working-directory: ${{ env.working-directory }}
    - uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORT_ID }}
      with:
        workingDirectory: ${{ env.working-directory }}
        coverageLocations: report/lcov.info:lcov
          