# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: CI

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
  push:
    branches: [ master ]
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

  test:
    needs: [ build ]
    name: test
    runs-on: ubuntu-latest
    env: 
      working-directory: ./src
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo npm install
      working-directory: ${{ env.working-directory }}
    - run: cp .env.example .env
      working-directory: ${{ env.working-directory }}
    - run: sudo npm run test
      working-directory: ${{ env.working-directory }}
