# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: CI

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - '.github/**'
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - '.github/**'

jobs:
  test:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        node: [ '14' ]
    name: test/node ${{ matrix.node }}/${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node }}
    - run: npm run install
    - run: npm run test
  coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    env: 
      working-directory: ./src
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: '14'
    - run: npm run install
    - uses: paambaati/codeclimate-action@v2.2.4
      env:
        CC_TEST_REPORTER_ID: {{ secrets.CC_TEST_REPORT_ID }}
      with:
        coverageCommand: npm run coverage
